-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 00:05:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `maturao_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maturao_role` ;

CREATE TABLE IF NOT EXISTS `maturao_role` (
  `id` VARCHAR(255) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturao_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maturao_user` ;

CREATE TABLE IF NOT EXISTS `maturao_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `id_role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maturao_user_maturao_role_idx` (`id_role` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_maturao_user_maturao_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `maturao_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturao_article_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maturao_article_state` ;

CREATE TABLE IF NOT EXISTS `maturao_article_state` (
  `id` VARCHAR(255) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturao_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maturao_article` ;

CREATE TABLE IF NOT EXISTS `maturao_article` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `abstract` TEXT NOT NULL,
  `pdf_file` VARCHAR(255) NOT NULL,
  `id_article_state` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maturao_article_maturao_user1_idx` (`id_user` ASC),
  INDEX `fk_maturao_article_maturao_article_state1_idx` (`id_article_state` ASC),
  CONSTRAINT `fk_maturao_article_maturao_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `maturao_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maturao_article_maturao_article_state1`
    FOREIGN KEY (`id_article_state`)
    REFERENCES `maturao_article_state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturao_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maturao_review` ;

CREATE TABLE IF NOT EXISTS `maturao_review` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL,
  `id_article` INT UNSIGNED NOT NULL,
  `content_quality` TINYINT UNSIGNED NULL,
  `technical_quality` TINYINT UNSIGNED NULL,
  `language_quality` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maturao_review_maturao_user1_idx` (`id_user` ASC),
  INDEX `fk_maturao_review_maturao_article1_idx` (`id_article` ASC),
  CONSTRAINT `fk_maturao_review_maturao_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `maturao_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maturao_review_maturao_article1`
    FOREIGN KEY (`id_article`)
    REFERENCES `maturao_article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Placeholder table for view `maturao_article_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturao_article_view` (`id` INT, `id_user` INT, `user` INT, `display_name` INT, `abstract` INT, `pdf_file` INT, `id_article_state` INT, `article_state` INT);

-- -----------------------------------------------------
-- View `maturao_article_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maturao_article_view`;
DROP VIEW IF EXISTS `maturao_article_view` ;
CREATE  OR REPLACE VIEW `maturao_article_view` AS
    SELECT 
        `maturao_article`.id,
        `maturao_article`.id_user,
        `maturao_user`.login AS `user`,
        `maturao_article`.display_name,
        `maturao_article`.abstract,
        `maturao_article`.pdf_file,
        `maturao_article`.id_article_state,
        `maturao_article_state`.display_name AS `article_state`
    FROM
        `maturao_article`
            INNER JOIN
        `maturao_user` ON `maturao_article`.id_user = `maturao_user`.id
            INNER JOIN
        `maturao_article_state` ON `maturao_article`.id_article_state = `maturao_article_state`.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `maturao_role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `maturao_role` (`id`, `display_name`) VALUES ('admin', 'Admin');
INSERT INTO `maturao_role` (`id`, `display_name`) VALUES ('author', 'Autor');
INSERT INTO `maturao_role` (`id`, `display_name`) VALUES ('reviewer', 'Recenzent');

COMMIT;


-- -----------------------------------------------------
-- Data for table `maturao_user`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `maturao_user` (`id`, `login`, `password`, `id_role`) VALUES (1, 'admin', '$2y$10$ZUn4brntAvQljqLCACL72.YtsjXmj.oQcx3Oj14x4/I.bIZHp0GCa', 'admin');
INSERT INTO `maturao_user` (`id`, `login`, `password`, `id_role`) VALUES (2, 'roman', '$2y$10$ZUn4brntAvQljqLCACL72.YtsjXmj.oQcx3Oj14x4/I.bIZHp0GCa', 'reviewer');
INSERT INTO `maturao_user` (`id`, `login`, `password`, `id_role`) VALUES (3, 'adam', '$2y$10$ZUn4brntAvQljqLCACL72.YtsjXmj.oQcx3Oj14x4/I.bIZHp0GCa', 'author');

COMMIT;


-- -----------------------------------------------------
-- Data for table `maturao_article_state`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `maturao_article_state` (`id`, `display_name`) VALUES ('reviewing', 'V hodnocení');
INSERT INTO `maturao_article_state` (`id`, `display_name`) VALUES ('accepted', 'Schválen');
INSERT INTO `maturao_article_state` (`id`, `display_name`) VALUES ('denied', 'Zamítnut');

COMMIT;


-- -----------------------------------------------------
-- Data for table `maturao_article`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `maturao_article` (`id`, `id_user`, `display_name`, `abstract`, `pdf_file`, `id_article_state`) VALUES (1, 3, 'Testovaci 1', 'testset', 'soubor', 'reviewing');
INSERT INTO `maturao_article` (`id`, `id_user`, `display_name`, `abstract`, `pdf_file`, `id_article_state`) VALUES (2, 3, 'Testovaci 2', 'testabst', 'souborr', 'accepted');

COMMIT;


-- -----------------------------------------------------
-- Data for table `maturao_review`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `maturao_review` (`id`, `id_user`, `id_article`, `content_quality`, `technical_quality`, `language_quality`) VALUES (1, 2, 1, 50, 60, 70);
INSERT INTO `maturao_review` (`id`, `id_user`, `id_article`, `content_quality`, `technical_quality`, `language_quality`) VALUES (2, 2, 2, 100, 90, 100);

COMMIT;

